bot:
#  name: ${BOT_NAME}
#  token: ${BOT_TOKEN}
  name: MyFirstSpringDemo_bot
  token: 7197862705:AAGj6ZXbpc-qJsD_E59p9YlF7H4-n8Pc1gI


restclient:
#  url: ${MIDDLE_SERVICE_URL}
  url: http://localhost:8081